---
source: "https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports_us"
corruption:
- nameAttribute: "Region"
  enable: true
  value: 0
- nameAttribute: "Confirmed"
  enable: true
  value: 0
- nameAttribute: "Death"
  enable: true
  value: 0
- nameAttribute: "Recovered"
  enable: true
  value: 0
- nameAttribute: "Active"
  enable: true
  value: 0
- nameAttribute: "Rate"
  enable: true
  value: 0
saveSettings:
  initFolder: "G:\\_ИНСТИТУТ\\3 КУРС\\Предмети\\MatLab\\DataManager\\initFolder"
  processedFolder: "G:\\_ИНСТИТУТ\\3 КУРС\\Предмети\\MatLab\\DataManager\\processedFolder"
